apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ir51p9izf-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ir51p9izf-dotnet-basic-gitops